
model: 'PPO'
policy: 'MlpPolicy'
learning_rate: 0.0003
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.95
clip_range: 0.2
ent_coef: 0.0
vf_coef: 0.5
max_grad_norm: 0.5
deterministic: True
seed: 11
scenario_path: 
tb_logs: True
episodes: 100
max_steer: 0.5
max_accel: 5

